### ISSUE TITLE
about environment set (tf version?)

### ISSUE THREAD

**Issue by hongyinjie** [mvoelk/ssd_detectors#46]
environment set1: (use tf2， follow the environment.ipynb)
OS               debian stretch/sid 
Python           3.7.4
NumPy            1.17.2
Pandas           1.0.4
Matplotlib       3.2.1
OpenCV           3.4.3
TensorFlow       2.0.0-beta1
Keras            2.2.4-tf
tqdm             4.46.1
imageio          2.6.1

environment set2:
OS               debian stretch/sid 
Python           3.7.5
NumPy            1.18.0
Pandas           0.25.3
Matplotlib       3.2.1
OpenCV           3.4.3
TensorFlow       1.15.0
Keras            2.2.4-tf
tqdm             4.41.1
imageio          2.8.0

when use set1:
it run wrong  in PriorUtil:  

Traceback (most recent call last):
  File "/mnt/downloads/github_src/ssd_detectors/SSD_predict.py", line 40, in <module>
    prior_util = PriorUtil(model)
  File "/mnt/downloads/github_src/ssd_detectors/ssd_utils.py", line 353, in __init__
    self.update_priors()
  File "/mnt/downloads/github_src/ssd_detectors/ssd_utils.py", line 375, in update_priors
    m.compute_priors()
  File "/mnt/downloads/github_src/ssd_detectors/ssd_utils.py", line 193, in compute_priors
    linx = np.array([(0.5 + i) for i in range(map_w)]) * step_x
TypeError: 'NoneType' object cannot be interpreted as an integer

Traceback (most recent call last):
  File "/mnt/downloads/github_src/ssd_detectors/SL_end2end_predict.py", line 41, in <module>
    prior_util = PriorUtil(model)
  File "/mnt/downloads/github_src/ssd_detectors/sl_utils.py", line 45, in __init__
    if i > 0 and np.all(np.array(previous_map_size) != np.array(map_size)*2):
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

when use set2 
SSD_predict and SL_predict
it works well.

but alse print that:
****
layer missing zero_padding2d_5
    file  []
****
what is wrong...

when use set2  run 
****
layer missing reshape_1
    file  []
something went wrong bidirectional_1
    model [[512, 1024], [256, 1024], [1024], [512, 1024], [256, 1024], [1024]]
    file  [(512, 768), (256, 768), (768,), (512, 768), (256, 768), (768,)]
Layer weight shape (512, 1024) not compatible with provided weight shape (512, 768)
layer missing bidirectional_2
    file  [(512, 768), (256, 768), (768,), (512, 768), (256, 768), (768,)]
layer missing label_input
    file  []
layer missing input_length
    file  []
layer missing label_length
    file  []
layer missing ctc
    file  []
****

Traceback (most recent call last):
  File "/mnt/downloads/github_src/ssd_detectors/SL_end2end_predict.py", line 152, in <module>
    res_crnn = crnn_model.predict(words)
  File "/home/hyj/anaconda3/envs/py37tf15/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 908, in predict
    use_multiprocessing=use_multiprocessing)
  File "/home/hyj/anaconda3/envs/py37tf15/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 723, in predict
    callbacks=callbacks)
  File "/home/hyj/anaconda3/envs/py37tf15/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 394, in model_iteration
    batch_outs = f(ins_batch)
  File "/home/hyj/anaconda3/envs/py37tf15/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/home/hyj/anaconda3/envs/py37tf15/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(3, 512), b.shape=(512, 256), m=3, n=256, k=512
	 [[{{node bidirectional/forward_lstm_1/while/MatMul}}]]
	 [[softmax/truediv/_209]]
  (1) Internal: Blas GEMM launch failed : a.shape=(3, 512), b.shape=(512, 256), m=3, n=256, k=512
	 [[{{node bidirectional/forward_lstm_1/while/MatMul}}]]
0 successful operations.
0 derived errors ignored.
****

thank you !

**Comment by mvoelk** [comment]
> layer missing zero_padding2d_5

You can ignore this message. We do not need a extra layer for padding :)

The `master` branch is up to date for TF 2.x. I'm not sure, 2.0.0-beta1 may be too low. You could try to update to 2.2, what could be painful on Stretch. The `tf1` branch should run with TF 1.15 and Keras, not TF-Keras. You can ignore the `tf2` branch.

**Comment by hongyinjie** [comment]
> > layer missing zero_padding2d_5
> 
> You can ignore this message. We do not need a extra layer for padding :)
> 
> The `master` branch is up to date for TF 2.x. I'm not sure, 2.0.0-beta1 may be too low. You could try to update to 2.2, what could be painful on Stretch. The `tf1` branch should run with TF 1.15 and Keras, not TF-Keras. You can ignore the `tf2` branch.

thank you very much!
I will try it immediately
