### ISSUE TITLE
Problem during with Crowd Human dataset

### ISSUE THREAD

**Issue by clueless2020** [mvoelk/ssd_detectors#61]
Thank you for this awesome repository. The code works fin for VOC 2007 dataset. However, for Crowd Person dataset, I am getting the following error during model training in DSOD_train.ipynb.

The error

--------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/context.py in execution_mode(mode)
   2112       ctx.executor = executor_new
-> 2113       yield
   2114     finally:

/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py in _next_internal(self)
    729     with context.execution_mode(context.SYNC):
--> 730       ret = gen_dataset_ops.iterator_get_next(
    731           self._iterator_resource,

/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_dataset_ops.py in iterator_get_next(iterator, output_types, output_shapes, name)
   2578     except _core._NotOkStatusException as e:
-> 2579       _ops.raise_from_not_ok_status(e, name)
   2580     except _core._FallbackException:

/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6861   # pylint: disable=protected-access
-> 6862   six.raise_from(core._status_to_exception(e.code, message), None)
   6863   # pylint: enable=protected-access

~/.local/lib/python3.8/site-packages/six.py in raise_from(value, from_value)

UnknownError: IndexError: tuple index out of range
Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 247, in __call__
    return func(device, token, args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 135, in __call__
    ret = self._func(*args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/home/user5/detection/pedestrian/ssd_detectors/ssd_data.py", line 506, in get_sample
    img_tmp, y_tmp = self.random_sized_crop(img, y)

  File "/home/user5/detection/pedestrian/ssd_detectors/ssd_data.py", line 452, in random_sized_crop
    num_coords = target.shape[1] - 1

IndexError: tuple index out of range

	 [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

UnknownError                              Traceback (most recent call last)
<ipython-input-11-50d4b7660236> in <module>
     20 
     21     for i in tqdm(range(gen_train.num_batches), 'training', leave=False):
---> 22         x, y_true = next(iterator_train)
     23         metric_values = step(x, y_true, training=True)
     24         metric_util.update(metric_values, training=True)

/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py in __next__(self)
    745   def __next__(self):
    746     try:
--> 747       return self._next_internal()
    748     except errors.OutOfRangeError:
    749       raise StopIteration

/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py in _next_internal(self)
    737         return self._element_spec._from_compatible_tensor_list(ret)  # pylint: disable=protected-access
    738       except AttributeError:
--> 739         return structure.from_compatible_tensor_list(self._element_spec, ret)
    740 
    741   @property

/usr/lib/python3.8/contextlib.py in __exit__(self, type, value, traceback)
    129                 value = type()
    130             try:
--> 131                 self.gen.throw(type, value, traceback)
    132             except StopIteration as exc:
    133                 # Suppress StopIteration *unless* it's the same exception that

/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/context.py in execution_mode(mode)
   2114     finally:
   2115       ctx.executor = executor_old
-> 2116       executor_new.wait()
   2117 
   2118 

/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/executor.py in wait(self)
     67   def wait(self):
     68     """Waits for ops dispatched in this executor to finish."""
---> 69     pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
     70 
     71   def clear_error(self):

UnknownError: IndexError: tuple index out of range
Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 247, in __call__
    return func(device, token, args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/script_ops.py", line 135, in __call__
    ret = self._func(*args)

  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/home/user5/detection/pedestrian/ssd_detectors/ssd_data.py", line 506, in get_sample
    img_tmp, y_tmp = self.random_sized_crop(img, y)

  File "/home/user5/detection/pedestrian/ssd_detectors/ssd_data.py", line 452, in random_sized_crop
    num_coords = target.shape[1] - 1

IndexError: tuple index out of range

	 [[{{node EagerPyFunc}}]]

**Comment by mvoelk** [comment]
Empty ground truth?
